---
title: Errors
---

## SurrealError

`SurrealError` is the base class that almost all error objects explicitly thrown by this SDK inherit from. This class inherits from the JavaScript `Error` class. This error object is rarely thrown by itself but is basically thrown as an inherited error object with a special meaning. We recommend using it to easily classify whether an error supplemented by a `try-catch` construct is an error explicitly thrown by this SDK.

`.name: "SurrealError"`
:   Error name.

`.message`
:   Error message.

`.stack`
:   A stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

## SurrealTypeError

Inherits from: `SurrealError`

This error is thrown when an input value or other validation fails.

`.name: "SurrealTypeError"`
:   Error name.

`.expected`
:   Expected data format.

`.actual`
:   String representation of the actual value.

## SurrealAggregateError

Inherits from: `SurrealError`

This error aggregates multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   Error name.

`.cause: unknown[]`
:   Each element of the array contains an error, an error message, etc.

## CircularReferenceError

Inherits from: `SurrealError`

This error is thrown when a circular reference is detected. It is mainly thrown during the process of converting a JavaScript value to another format, when an object is detected that is the same as its parent object.

`.name: "CircularReferenceError"`
:   Error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherits from: `SurrealError`

This error is thrown when a number is outside the allowed range.

`.name: "NumberRangeError"`
:   Error name.

`.range`
:   Expected range.

`.actual`
:   Actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherits from: `SurrealError`

This error is thrown if it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   Error name.

## UnreachableError

Inherits from: `SurrealError`

This error is thrown when unreachable code is reached. If this error is thrown, you have probably encountered a bug in this SDK.

`.name: "UnreachableError"`
:   Error name.

## CircularEngineReferenceError

Inherits from: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines when connecting to a database.

`.name: "CircularEngineReferenceError"`
:   Error name.

`.seen: string[]`
:   List of protocol names that were passed through before the circular reference occurred.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, the engine for the `https` protocol is set to use the engine configured for `http`, but the engine for the `http` protocol is set to use the engine configured for `https`, resulting in a circular reference error.

## EngineNotFoundError

Inherits from: `SurrealError`

This error is thrown when attempting to connect with a protocol for which no engine is configured.

`.name: "EngineNotFoundError"`
:   Error name.

`.protocol: string`
:   The name of the protocol to connect to.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherits from: `SurrealError`

This error is thrown when a client attempts to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   Error name.

`.endpoint1: string`
:   One of the endpoints.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the end of the passed URL if it doesn't already end with it. Therefore, if one endpoint URL path ends with `/rpc`, it may not result in an error, contrary to its appearance:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different namespaces at the same time.

`.name: "NamespaceConflictError"`
:   Error name.

`.namespace1: string`
:   One of the namespaces.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different databases at the same time.

`.name: "DatabaseConflictError"`
:   Error name.

`.database1: string`
:   One of the databases.

`.database2: string`
:   The other database.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Inherits from: `SurrealError`

This error is thrown if a namespace is not selected before selecting a database. It is also thrown if you try to unselect a namespace while a database is selected.

`.name: "MissingNamespaceError"`
:   Error name.

`.database: string`
:   Database name.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherits from: `SurrealError`

This error is thrown when the RPC response indicates an error. There is no problem with the communication by the connected protocol or decoding of the response body, but it means that SurrealDB could not process the RPC request.

`.name: "RpcResponseError"`
:   Error name.

`.id?: string`
:   An ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   Although not explicitly stated in the SurrealDB documentation, this is probably the JSON-RPC error code.

## QueryFailedError

Inherits from: `SurrealAggregateError`

This error is thrown when a query fails.

`.name: "QueryFailedError"`
:   Error name.

`.cause: string[]`
:   List of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

Inherits from: `SurrealError`

This error indicates that the connection was forcibly terminated.

`.name: "Disconnected"`
:   Error name.

For example, you get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

Inherits from: `SurrealError`

This indicates that the error originated from the engine. It is dispatched via an event listener.

`.name: "EngineError"`
:   Error name.

`.fatal: boolean | undefined`
:   Indicates whether the error is fatal.

## HttpEngineError

Inherits from: `EngineError`

This indicates that the error originated from the HTTP engine. Currently it is only defined and not used.

`.name: "HttpEngineError"`
:   Error name.

## WebSocketEngineError

Inherits from: `EngineError`

This indicates that the error originated from the WebSocket engine. It is used when the response body fails to parse before finding the ID that identifies the RPC request, when an error event is received from the WebSocket object, or when the WebSocket connection is closed.

`.name: "WebSocketEngineError"`
:   Error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that an "error" event was received from an instance of `WebSocket`[^1].
    - `3151`: Indicates that an error occurred within the "open" event handler registered by the WebSocket engine. This is most likely due to a `StateTransitionError` occurring during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred within the "message" event handler registered by the WebSocket engine. There are many possible causes, but it is likely that a `ResponseError` or `RpcResponseError` was thrown within the event handler. This could be caused by requesting a SurrealQL custom query with incorrect syntax in the `.query()` method or by making a request with invalid RPC parameters. In that case, the RPC caller method will (by default) time out after 5 seconds and fail.
    - `3153`: Indicates that sending or receiving a ping failed. This may be a temporary error, but if it is received continuously, the connection may not be maintained.
    - `3154`: Indicates that an error occurred within the "close" event handler registered by the WebSocket engine. This is most likely due to a `StateTransitionError` occurring during the transition from the closing state to the closed state.
:   Note that the following status codes are excluded from the above. This SDK does not treat them as errors:
    - `1000`: Closed normally.
    - `1001`: Early closure is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` may be a class that the runtime defines in global variables, or a class from the `ws` SDK.

## StateTransitionError

Inherits from: `SurrealAggregateError`

This error is thrown when an event listener fails to execute during a state transition.

`.name: "StateTransitionError"`
:   Error name.

`.from: string`
:   The state at the start of the state transition.

`.to: string`
:   The state to transition to.

`.fallback: string`
:   The alternate state to transition to if the state transition fails. If it has the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherits from: `SurrealError`

This error is thrown when an attempt is made to send an RPC request while disconnected.

`.name: "ConnectionUnavailableError"`
:   Error name.

## ResponseError

Inherits from: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. It differs from `RpcResponseError`.

`.name: "ResponseError"`
:   Error name.

## CborError

Inherits from: `SurrealError`

This is the class that all CBOR-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

`.name: "CborError"`
:   Error name.

## CborWellFormednessError

Inherits from: `CborError`

This is the class that all CBOR decoding-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

See "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)" in Appendix F of RFC8949.

`.name: "CborWellFormednessError"`
:   Error name.

## CborTooMuchDataError

Inherits from: `CborWellFormednessError`

This indicates that there were unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   Error name.

## CborTooLittleDataError

Inherits from: `CborWellFormednessError`

This indicates that the input bytes were incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   Error name.

## CborSyntaxError

Inherits from: `CborWellFormednessError`

Indicates that the input bytes did not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   Error name.

## CborMaxDepthReachedError

Inherits from: `CborError`

Error thrown when the maximum depth of a JavaScript object is reached during CBOR encoding or decoding. The depth is incremented by 1 for each object or array entered.

`.name: "CborMaxDepthReachedError"`
:   Error name.

`.maxDepth: number`
:   Maximum depth.

## CborUnsafeMapKeyError

Inherits from: `CborError`

Error thrown when an unsafe map key is encountered during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   Error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
